# Generated by Django 5.2.8 on 2025-12-05 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialeventregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specialeventregistration',
            name='occurrence_date',
            field=models.DateField(blank=True, help_text='The specific date of the event occurrence this registration is for', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='specialeventregistration',
            unique_together={('event', 'user', 'occurrence_date')},
        ),
    ]
