# Generated by Django 5.2.8 on 2025-12-05 15:17

from django.db import migrations


def populate_occurrence_date(apps, schema_editor):
    SpecialEventRegistration = apps.get_model('special_events', 'SpecialEventRegistration')
    
    # For existing registrations, set occurrence_date to the event's date
    for registration in SpecialEventRegistration.objects.filter(occurrence_date__isnull=True):
        registration.occurrence_date = registration.event.date
        registration.save()


def reverse_populate_occurrence_date(apps, schema_editor):
    # No reverse operation needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0002_alter_specialeventregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_occurrence_date, reverse_populate_occurrence_date),
    ]
