# Generated by Django 5.2.8 on 2025-12-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0003_populate_occurrence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialeventregistration',
            name='occurrence_date',
            field=models.DateField(help_text='The specific date of the event occurrence this registration is for'),
        ),
    ]



