# Generated by Django 5.2.8 on 2025-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0004_make_occurrence_date_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional price for the event', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='specialevent',
            name='show_price',
            field=models.BooleanField(default=False, help_text='Toggle to show/hide price on user-facing page'),
        ),
    ]
