# Generated by Django 5.2.8 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0005_specialevent_price_specialevent_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='location_id',
            field=models.CharField(blank=True, help_text='GHL location ID for this event', max_length=100, null=True),
        ),
    ]
