# Generated by Django 5.2.8 on 2026-01-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0009_specialevent_is_auto_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEventPausedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the occurrence to pause')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paused_dates', to='special_events.specialevent')),
            ],
            options={
                'verbose_name': 'Paused Event Date',
                'ordering': ['date'],
                'unique_together': {('event', 'date')},
            },
        ),
    ]
