# Generated by Django 5.2.8 on 2026-01-21 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_events', '0010_specialeventpauseddate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect to after event registration payment (if upfront_payment is True)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='specialevent',
            name='upfront_payment',
            field=models.BooleanField(default=False, help_text='If True, users must pay upfront to register. This creates a temporary hold on the spot until payment is confirmed.'),
        ),
        migrations.CreateModel(
            name='TempSpecialEventBooking',
            fields=[
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField(help_text='The specific date of the event occurrence')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='External payment ID', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration time for temp booking (default 9 mins)', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_bookings', to='special_events.specialevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_event_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary Event Booking',
                'verbose_name_plural': 'Temporary Event Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
