# Generated by Django 4.2.7 on 2026-04-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_category_assets"),
        ("special_events", "0011_specialevent_redirect_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialevent",
            name="category_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a category asset for asset-specific group sessions. Leave blank for facility-wide events.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_events",
                to="categories.categoryasset",
            ),
        ),
    ]
