# Generated by Django 5.2.8 on 2025-11-14 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
        ('simulators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('simulator', 'Simulator'), ('coaching', 'Coaching')], max_length=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=10)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL)),
                ('coaching_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaching.coachingpackage')),
                ('simulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulators.simulator')),
            ],
        ),
    ]
