# Generated by Django 5.2.8 on 2025-11-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('coaching', '0002_coachingpackage_session_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='coaching.coachingpackagepurchase'),
        ),
    ]
