# Generated by Django 5.2.8 on 2025-11-19 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_package_purchase'),
        ('simulators', '0003_simulatorcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='simulator_credit_redemption',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_booking', to='simulators.simulatorcredit'),
        ),
    ]
