# Generated by Django 5.2.8 on 2025-12-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_simulator_credit_redemption'),
        ('coaching', '0010_simulatorpackage_simulatorpackagepurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='simulator_package_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='coaching.simulatorpackagepurchase'),
        ),
    ]
