# Generated by Django 5.2.8 on 2025-12-08 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_simulator_package_purchase'),
        ('simulators', '0006_simulator_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempBooking',
            fields=[
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration time for temp booking (default 24 hours)', null=True)),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_bookings', to='simulators.simulator')),
            ],
            options={
                'verbose_name': 'Temporary Booking',
                'verbose_name_plural': 'Temporary Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
