# Generated by Django 5.2.8 on 2025-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_tempbooking_simulator_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempbooking',
            name='duration_minutes',
            field=models.IntegerField(help_text='Duration per simulator in minutes'),
        ),
    ]
