# Generated by Django 5.2.8 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_tempbooking_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location_id',
            field=models.CharField(blank=True, help_text='GHL location ID for this booking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tempbooking',
            name='location_id',
            field=models.CharField(blank=True, help_text='GHL location ID for this temp booking', max_length=100, null=True),
        ),
    ]
