# Generated by Django 5.2.8 on 2026-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_location_id_tempbooking_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_tpi_assessment',
            field=models.BooleanField(default=False, help_text='If True, this booking was made using a TPI Assessment package'),
        ),
    ]
