# Generated by Django 5.2.8 on 2026-01-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_booking_constraints'),
        ('bookings', '0009_booking_is_tpi_assessment'),
    ]

    operations = [
    ]
