# Generated by Django 5.2.8 on 2026-01-15 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_merge_20260115_1950'),
        ('coaching', '0021_coachingpackage_is_tpi_assessment'),
        ('simulators', '0008_simulator_location_id_alter_simulator_bay_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbooking',
            name='payment_id',
            field=models.CharField(blank=True, help_text='External payment ID for idempotency protection', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tempbooking',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the temp booking was converted to a real booking', null=True),
        ),
        migrations.AddField(
            model_name='tempbooking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='reserved', help_text='Status of the temporary booking reservation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['simulator', 'start_time', 'booking_type', 'status'], name='booking_conflict_check_idx'),
        ),
        migrations.AddIndex(
            model_name='tempbooking',
            index=models.Index(fields=['status', 'expires_at'], name='tempbook_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='tempbooking',
            index=models.Index(condition=models.Q(('payment_id__isnull', False)), fields=['payment_id'], name='tempbook_payment_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tempbooking',
            index=models.Index(fields=['simulator', 'start_time', 'end_time', 'status'], name='tempbook_avail_check_idx'),
        ),
    ]
