# Generated by Django 4.2.7 on 2026-04-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_seed_default_service_categories"),
        ("bookings", "0011_tempbooking_payment_id_tempbooking_processed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Service category for non-legacy category bookings (Phase E).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="categories.servicecategory",
            ),
        ),
    ]
