# Generated by Django 5.2.8 on 2026-04-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_category_asset'),
        ('categories', '0003_category_assets'),
        ('simulators', '0008_simulator_location_id_alter_simulator_bay_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tempbooking',
            name='tempbook_avail_check_idx',
        ),
        migrations.AddField(
            model_name='tempbooking',
            name='category_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_bookings', to='categories.categoryasset'),
        ),
        migrations.AddField(
            model_name='tempbooking',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_bookings', to='categories.servicecategory'),
        ),
        migrations.AlterField(
            model_name='tempbooking',
            name='duration_minutes',
            field=models.IntegerField(help_text='Duration per simulator/asset in minutes'),
        ),
        migrations.AlterField(
            model_name='tempbooking',
            name='simulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_bookings', to='simulators.simulator'),
        ),
        migrations.AlterField(
            model_name='tempbooking',
            name='simulator_count',
            field=models.IntegerField(default=1, help_text='Number of simulators or assets to book'),
        ),
        migrations.AddIndex(
            model_name='tempbooking',
            index=models.Index(fields=['start_time', 'end_time', 'status'], name='tempbook_gen_avail_idx'),
        ),
    ]
