# Generated by Django 5.2.8 on 2025-11-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='simulators.simulator')),
            ],
            options={
                'verbose_name_plural': 'Simulator Availabilities',
                'unique_together': {('simulator', 'day_of_week', 'start_time')},
            },
        ),
    ]
