# Generated by Django 5.2.8 on 2025-11-19 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_package_purchase'),
        ('simulators', '0002_simulatoravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('redeemed', 'Redeemed'), ('revoked', 'Revoked')], default='available', max_length=20)),
                ('reason', models.CharField(choices=[('cancellation', 'Cancellation Refund'), ('manual', 'Manual Adjustment')], default='cancellation', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_credits', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_simulator_credits', to=settings.AUTH_USER_MODEL)),
                ('source_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_simulator_credits', to='bookings.booking')),
            ],
        ),
    ]
