# Generated by Django 5.2.8 on 2025-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0003_simulatorcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='hourly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate (in USD) for normal simulator sessions.', max_digits=8, null=True),
        ),
    ]
