# Generated by Django 5.2.8 on 2025-12-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0004_simulator_hourly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorcredit',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours in this credit', max_digits=6),
        ),
        migrations.AddField(
            model_name='simulatorcredit',
            name='hours_remaining',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining hours available in this credit', max_digits=6),
        ),
    ]
