# Generated by Django 5.2.8 on 2025-12-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0005_simulatorcredit_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='redirect_url',
            field=models.URLField(blank=True, default='https://chatgpt.com', help_text='URL to redirect to after simulator booking payment', max_length=500, null=True),
        ),
    ]
