# Generated by Django 5.2.8 on 2025-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0006_simulator_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect to after simulator booking payment', max_length=500, null=True),
        ),
    ]
