# Generated by Django 5.2.8 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0007_alter_simulator_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='location_id',
            field=models.CharField(blank=True, help_text='GHL location ID for this simulator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='bay_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='simulator',
            unique_together={('bay_number', 'location_id')},
        ),
    ]
