# Generated by Django 5.2.8 on 2026-09-14 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0008_simulator_location_id_alter_simulator_bay_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when this bay is blocked')),
                ('start_time', models.TimeField(blank=True, help_text='Start time of block (empty = full-day). Wall-clock in center local timezone.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of block (empty = full-day). Wall-clock in center local timezone.', null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulator_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='simulators.simulator')),
            ],
            options={
                'verbose_name': 'Simulator Blocked Date',
                'verbose_name_plural': 'Simulator Blocked Dates',
                'ordering': ['date', 'start_time'],
                'unique_together': {('simulator', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
