# Generated by Django 5.2.8 on 2025-11-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Step 1: Remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together=set(),
        ),
        # Step 2: Add the new date field
        migrations.AddField(
            model_name='staffavailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        # Step 3: Remove the old day_of_week field
        migrations.RemoveField(
            model_name='staffavailability',
            name='day_of_week',
        ),
        # Step 4: Add new unique_together constraint with date field
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'date', 'start_time')},
        ),
    ]
