# Generated by Django 5.2.8 on 2025-11-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staffavailability_unique_together_and_more'),
    ]

    operations = [
        # Step 1: Remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together=set(),
        ),
        # Step 2: Add the new day_of_week field
        migrations.AddField(
            model_name='staffavailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        # Step 3: Remove the old date field
        migrations.RemoveField(
            model_name='staffavailability',
            name='date',
        ),
        # Step 4: Add new unique_together constraint with day_of_week
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'day_of_week', 'start_time')},
        ),
    ]
