# Generated by Django 5.2.8 on 2025-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staffavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ghl_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
