# Generated by Django 5.2.8 on 2025-11-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ghl_contact_id_user_ghl_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='If True, user cannot login or access the system'),
        ),
    ]
