# Generated by Django 5.2.8 on 2025-12-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_staffdayavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth (optional)', null=True),
        ),
    ]
