# Generated by Django 5.2.8 on 2026-01-30 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_liabilitywaiver'),
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiabilityWaiverAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(help_text='Timestamp when user accepted the waiver (stored in UTC)')),
                ('waiver_content_hash', models.CharField(help_text='Hash of waiver content at time of acceptance to detect content changes', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_acceptances', to=settings.AUTH_USER_MODEL)),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='admin_panel.liabilitywaiver')),
            ],
            options={
                'verbose_name': 'Liability Waiver Acceptance',
                'verbose_name_plural': 'Liability Waiver Acceptances',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'waiver')},
            },
        ),
    ]
