# Generated by Django 5.2.8 on 2026-02-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_liabilitywaiveracceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when staff is blocked/unavailable')),
                ('reason', models.CharField(blank=True, help_text='Optional reason for blocking', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Blocked Date',
                'verbose_name_plural': 'Staff Blocked Dates',
                'ordering': ['date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
