# Generated by Django 5.2.8 on 2026-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staffblockeddate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffblockeddate',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Staff Blocked Date', 'verbose_name_plural': 'Staff Blocked Dates'},
        ),
        migrations.AlterUniqueTogether(
            name='staffblockeddate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffblockeddate',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of block (leave empty for full-day block). Stored in local timezone (America/Halifax).', null=True),
        ),
        migrations.AddField(
            model_name='staffblockeddate',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of block (leave empty for full-day block). Stored in local timezone (America/Halifax).', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='staffblockeddate',
            unique_together={('staff', 'date', 'start_time', 'end_time')},
        ),
    ]
