# Generated by Django 5.2.8 on 2026-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_time_fields_to_blocked_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_color',
            field=models.CharField(blank=True, help_text='Hex color code for calendar display (e.g. #F97316)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffblockeddate',
            name='end_time',
            field=models.TimeField(blank=True, help_text="End time of block (leave empty for full-day block). Stored as wall-clock time in the center's local timezone.", null=True),
        ),
        migrations.AlterField(
            model_name='staffblockeddate',
            name='start_time',
            field=models.TimeField(blank=True, help_text="Start time of block (leave empty for full-day block). Stored as wall-clock time in the center's local timezone.", null=True),
        ),
    ]
