# Generated by Django 5.2.8 on 2026-04-21 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_seed_default_service_categories"),
        ("users", "0011_add_time_fields_to_blocked_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffblockeddate",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="End time of block (leave empty for full-day block). Stored as wall-clock time in the center's local timezone.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffblockeddate",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Start time of block (leave empty for full-day block). Stored as wall-clock time in the center's local timezone.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StaffCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary category for this staff member (used for display ordering).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="categories.servicecategory",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["staff", "admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Category",
                "verbose_name_plural": "Staff Categories",
                "ordering": ["-is_primary", "category__sort_order", "category__name"],
                "unique_together": {("staff", "category")},
            },
        ),
    ]
