# Generated by Django 5.2.8 on 2026-04-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_calendar_color_alter_staffblockeddate_end_time_and_more'),
        ('users', '0013_per_category_staff_availability'),
    ]

    operations = [
    ]
