# Generated by Django 5.2.8 on 2026-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20260427_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffblockeddate',
            name='end_time',
            field=models.TimeField(blank=True, help_text="End time of block (leave empty for full-day block). Wall-clock time in center's local timezone.", null=True),
        ),
        migrations.AlterField(
            model_name='staffblockeddate',
            name='start_time',
            field=models.TimeField(blank=True, help_text="Start time of block (leave empty for full-day block). Wall-clock time in center's local timezone.", null=True),
        ),
    ]
