# Generated by Django 5.2.8 on 2026-05-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ghl', '0004_add_logo_to_ghllocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSquareAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(blank=True, help_text='Square merchant_id returned during OAuth.', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Square OAuth access token (used for all API calls).')),
                ('refresh_token', models.TextField(blank=True, help_text='Square OAuth refresh token (use to get a new access_token).')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the current access_token expires.', null=True)),
                ('square_location_id', models.CharField(blank=True, help_text='Square Location ID for this merchant (used in payment calls).', max_length=255)),
                ('square_location_name', models.CharField(blank=True, help_text='Human-readable name of the Square location.', max_length=255)),
                ('is_connected', models.BooleanField(default=False, help_text='True once the golf center has successfully completed OAuth.')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ghl_location', models.OneToOneField(help_text='The GHL Location (golf center) this Square account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='square_account', to='ghl.ghllocation')),
            ],
            options={
                'verbose_name': 'Location Square Account',
                'verbose_name_plural': 'Location Square Accounts',
                'ordering': ['-connected_at'],
            },
        ),
    ]
