# Generated by Django 5.2.8 on 2026-06-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0026_add_membership_fields_to_simulator_package'),
        ('square_payments', '0001_location_square_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_location_id', models.CharField(help_text='GHL location ID — used to look up the Square OAuth token for billing.', max_length=100)),
                ('square_subscription_id', models.CharField(help_text='Square subscription ID returned by CreateSubscription.', max_length=100, unique=True)),
                ('square_plan_variation_id', models.CharField(blank=True, help_text='Square Catalog plan variation ID for this subscription plan.', max_length=100)),
                ('square_customer_id', models.CharField(blank=True, help_text='Square customer ID for this member.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of the current billing period.', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of the current billing period (next reset/charge date).', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When the subscription was canceled.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The user who subscribed.', on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(help_text='The membership-type SimulatorPackage.', on_delete=django.db.models.deletion.PROTECT, related_name='member_subscriptions', to='coaching.simulatorpackage')),
                ('purchase', models.OneToOneField(blank=True, help_text="The SimulatorPackagePurchase that holds this member's current hours.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_subscription', to='coaching.simulatorpackagepurchase')),
            ],
            options={
                'verbose_name': 'Member Subscription',
                'verbose_name_plural': 'Member Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
