# Generated by Django 5.2.8 on 2026-06-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0027_coachingpackage_is_membership_and_more'),
        ('square_payments', '0002_add_member_subscription_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersubscription',
            name='coaching_package',
            field=models.ForeignKey(blank=True, help_text='The membership-type CoachingPackage (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_subscriptions', to='coaching.coachingpackage'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='coaching_purchase',
            field=models.OneToOneField(blank=True, help_text="The CoachingPackagePurchase that holds this member's current hours/sessions (if applicable).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_subscription', to='coaching.coachingpackagepurchase'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='package',
            field=models.ForeignKey(blank=True, help_text='The membership-type SimulatorPackage (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_subscriptions', to='coaching.simulatorpackage'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='purchase',
            field=models.OneToOneField(blank=True, help_text="The SimulatorPackagePurchase that holds this member's current hours (if applicable).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_subscription', to='coaching.simulatorpackagepurchase'),
        ),
    ]
