# Generated by Django 5.2.8 on 2026-09-14 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0003_membersubscription_coaching_package_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.UUIDField(db_index=True)),
                ('payment_type', models.CharField(help_text='package | simulator | event | asset | asset:<id>', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('item_description', models.CharField(blank=True, default='', max_length=255)),
                ('payment_url', models.URLField(max_length=1000)),
                ('square_payment_link_id', models.CharField(blank=True, default='', max_length=100)),
                ('square_order_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ghl_location_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Payment Link',
                'verbose_name_plural': 'Pending Payment Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
