# Generated by Django 5.2.8 on 2025-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Name/description of the closure (e.g., 'Holiday', 'Maintenance')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about the closure')),
                ('start_date', models.DateField(help_text='Start date of closure')),
                ('end_date', models.DateField(help_text='End date of closure (same as start_date for single day)')),
                ('start_time', models.TimeField(blank=True, help_text='Start time of closure (leave empty for full day closure)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of closure (leave empty for full day closure)', null=True)),
                ('recurrence', models.CharField(choices=[('one_time', 'One Time (Specific Date Only)'), ('weekly', 'Weekly Recurring'), ('yearly', 'Yearly Recurring')], default='one_time', help_text='How often this closure repeats', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this closure is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Closed Day',
                'verbose_name_plural': 'Closed Days',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
