# Generated by Django 5.2.8 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedday',
            name='location_id',
            field=models.CharField(blank=True, help_text='GHL location ID for this closed day', max_length=100, null=True),
        ),
    ]
