# Generated by Django 5.2.8 on 2026-01-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_closedday_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiabilityWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(help_text="Rich text content as JSON array. Each item has 'type' (heading/paragraph), 'text', and optional 'bold', 'italic'")),
                ('is_active', models.BooleanField(default=True, help_text='If False, waiver will not be shown to users during login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liability Waiver',
                'verbose_name_plural': 'Liability Waivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
