# Generated by Django 5.2.8 on 2026-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_bulkuploadtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadtask',
            name='location_id',
            field=models.CharField(blank=True, help_text='Location ID this data belongs to', max_length=100, null=True),
        ),
    ]
