# Generated by Django 5.2.8 on 2026-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Services'), ('simulator', 'Simulator Bookings'), ('package', 'Package Purchases'), ('event', 'Special Event Registrations')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Total times this coupon can be used.', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='uses_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
