# Generated by Django 5.2.8 on 2026-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_options_coupon_applicable_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Services'), ('simulator', 'Simulator Bookings'), ('package', 'Package Purchases'), ('event', 'Special Event Registrations'), ('fitness', 'Fitness Packages')], default='all', max_length=20),
        ),
    ]
