# Generated by Django 5.2.8 on 2026-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_alter_coupon_applicable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Services'), ('simulator', 'Simulator Bookings'), ('package', 'Package Purchases'), ('event', 'Special Event Registrations')], default='all', max_length=20),
        ),
    ]
