# Generated by Django 5.2.8 on 2026-04-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_coupon_applicable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(default='all', help_text="Comma-separated list of applicable types (simulator, package, event, asset) or 'all'.", max_length=255),
        ),
    ]
