# Generated by Django 5.2.8 on 2026-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_coupon_applicable_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='item_label',
            field=models.CharField(blank=True, help_text='Specific item name (e.g. Package Title)', max_length=255),
        ),
    ]
