# Generated by Django 5.2.8 on 2026-04-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name in admin and API", max_length=120
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable key within a location scope", max_length=80
                    ),
                ),
                (
                    "customer_label",
                    models.CharField(
                        help_text="Short label shown on the customer booking UI",
                        max_length=120,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "location_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="GHL location id; empty string = default/fallback for all locations",
                        max_length=100,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_booking_type",
                    models.CharField(
                        blank=True,
                        choices=[("simulator", "Simulator"), ("coaching", "Coaching")],
                        help_text="Phase A: maps to existing booking_type. Null = not driven by legacy tabs yet.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location_id", "slug"),
                        name="categories_servicecategory_location_slug_uniq",
                    )
                ],
            },
        ),
    ]
