# Generated by Django 5.2.8 on 2025-11-18 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='session_count',
            field=models.PositiveIntegerField(default=1, help_text='How many coaching sessions are included.'),
        ),
        migrations.AddField(
            model_name='coachingpackage',
            name='session_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of a single session in minutes.'),
        ),
        migrations.CreateModel(
            name='CoachingPackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_total', models.PositiveIntegerField()),
                ('sessions_remaining', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_purchases', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='coaching.coachingpackage')),
            ],
            options={
                'verbose_name': 'Coaching Package Purchase',
                'verbose_name_plural': 'Coaching Package Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
