# Generated by Django 5.2.8 on 2025-11-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coachingpackage_session_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='gift_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration date for gift claim', null=True),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='gift_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='gift_token',
            field=models.CharField(blank=True, help_text='Unique token for gift claim', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='original_owner',
            field=models.ForeignKey(blank=True, help_text='Original purchaser for gifted packages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifted_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='package_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('gifted', 'Gifted')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='purchase_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('gift', 'Gift')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Phone number of gift recipient', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='SessionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_phone', models.CharField(help_text='Phone number of transfer recipient', max_length=15)),
                ('session_count', models.PositiveIntegerField(help_text='Number of sessions to transfer')),
                ('transfer_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('transfer_token', models.CharField(help_text='Unique token for transfer claim', max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for transfer claim', null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('package_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='coaching.coachingpackagepurchase')),
                ('to_user', models.ForeignKey(blank=True, help_text='Set when recipient accepts transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Transfer',
                'verbose_name_plural': 'Session Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
