# Generated by Django 5.2.8 on 2025-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_coachingpackagepurchase_gift_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='purchase_name',
            field=models.CharField(blank=True, default='', help_text='Custom label for this purchase', max_length=100),
        ),
    ]
