# Generated by Django 5.2.8 on 2025-11-28 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_coachingpackagepurchase_purchase_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingpackagepurchase',
            name='purchase_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('gift', 'Gift'), ('organization', 'Organization')], default='normal', max_length=15),
        ),
        migrations.CreateModel(
            name='OrganizationPackageMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Phone number of the member', max_length=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('package_purchase', models.ForeignKey(help_text='The organization package purchase this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='organization_members', to='coaching.coachingpackagepurchase')),
                ('user', models.ForeignKey(blank=True, help_text='User account if member has one (set when validated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_package_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Package Member',
                'verbose_name_plural': 'Organization Package Members',
                'ordering': ['added_at'],
                'unique_together': {('package_purchase', 'phone')},
            },
        ),
    ]
