# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_alter_coachingpackagepurchase_purchase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect to after package purchase', max_length=500, null=True),
        ),
    ]

