# Generated by Django 5.2.8

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coaching', '0006_coachingpackage_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPurchase',
            fields=[
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('purchase_type', models.CharField(choices=[('normal', 'Normal'), ('gift', 'Gift'), ('organization', 'Organization')], default='normal', max_length=20)),
                ('recipients', models.JSONField(default=list, help_text='List of recipient phone numbers (for gift/organization purchases)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration time for temp purchase (default 24 hours)', null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_purchases', to='coaching.coachingpackage')),
            ],
            options={
                'verbose_name': 'Temporary Purchase',
                'verbose_name_plural': 'Temporary Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=15)),
                ('purchase_type', models.CharField(choices=[('gift', 'Gift'), ('organization', 'Organization')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_pending_recipients', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_recipients', to='coaching.coachingpackage')),
                ('temp_purchase', models.ForeignKey(blank=True, help_text='Reference to the temp purchase that created this pending recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_recipients', to='coaching.temppurchase')),
            ],
            options={
                'verbose_name': 'Pending Recipient',
                'verbose_name_plural': 'Pending Recipients',
                'ordering': ['-created_at'],
                'unique_together': {('package', 'buyer', 'recipient_phone', 'purchase_type')},
            },
        ),
    ]

