# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0007_temppurchase_pendingrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrecipient',
            name='package_purchase',
            field=models.ForeignKey(
                blank=True,
                help_text='Direct link to the purchase this pending recipient belongs to. Set for organization purchases, None for gift purchases until recipient signs up.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pending_recipients_from_purchase',
                to='coaching.coachingpackagepurchase'
            ),
        ),
    ]

