# Generated by Django 5.2.8 on 2025-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0008_pendingrecipient_package_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='simulator_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of simulator hours included in this package (for simulator bookings).', max_digits=6),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='simulator_hours_remaining',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining simulator hours in this purchase', max_digits=6),
        ),
        migrations.AddField(
            model_name='coachingpackagepurchase',
            name='simulator_hours_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total simulator hours included in this purchase', max_digits=6),
        ),
    ]
