# Generated by Django 5.2.8 on 2025-12-08 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0009_coachingpackage_simulator_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Number of simulator hours included in this package', max_digits=6)),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect to after package purchase', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulator Package',
                'verbose_name_plural': 'Simulator Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorPackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_name', models.CharField(blank=True, default='', help_text='Custom label for this purchase', max_length=100)),
                ('hours_total', models.DecimalField(decimal_places=2, help_text='Total simulator hours in this purchase', max_digits=6)),
                ('hours_remaining', models.DecimalField(decimal_places=2, help_text='Remaining simulator hours in this purchase', max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('purchase_type', models.CharField(choices=[('normal', 'Normal'), ('gift', 'Gift')], default='normal', max_length=15)),
                ('recipient_phone', models.CharField(blank=True, help_text='Phone number of gift recipient', max_length=15, null=True)),
                ('gift_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=10, null=True)),
                ('gift_token', models.CharField(blank=True, help_text='Unique token for gift claim', max_length=64, null=True, unique=True)),
                ('package_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('gifted', 'Gifted')], default='active', max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_expires_at', models.DateTimeField(blank=True, help_text='Expiration date for gift claim', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_package_purchases', to=settings.AUTH_USER_MODEL)),
                ('original_owner', models.ForeignKey(blank=True, help_text='Original purchaser for gifted packages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifted_simulator_packages', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='coaching.simulatorpackage')),
            ],
            options={
                'verbose_name': 'Simulator Package Purchase',
                'verbose_name_plural': 'Simulator Package Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorHoursTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_phone', models.CharField(help_text='Phone number of transfer recipient', max_length=15)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Number of hours to transfer', max_digits=6)),
                ('transfer_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('transfer_token', models.CharField(help_text='Unique token for transfer claim', max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for transfer claim', null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_simulator_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, help_text='Set when recipient accepts transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_simulator_transfers', to=settings.AUTH_USER_MODEL)),
                ('package_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='coaching.simulatorpackagepurchase')),
            ],
            options={
                'verbose_name': 'Simulator Hours Transfer',
                'verbose_name_plural': 'Simulator Hours Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
