# Generated by Django 5.2.8 on 2025-12-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0010_simulatorpackage_simulatorpackagepurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppurchase',
            name='simulator_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_purchases', to='coaching.simulatorpackage'),
        ),
        migrations.AlterField(
            model_name='temppurchase',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_purchases', to='coaching.coachingpackage'),
        ),
    ]
