# Generated by Django 5.2.8 on 2025-12-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0011_temppurchase_simulator_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temppurchase',
            name='recipients',
            field=models.JSONField(blank=True, default=list, help_text='List of recipient phone numbers (for gift/organization purchases)'),
        ),
    ]
