# Generated by Django 5.2.8 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0012_alter_temppurchase_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='location_id',
            field=models.CharField(blank=True, help_text='GHL location ID for this package', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='simulatorpackage',
            name='location_id',
            field=models.CharField(blank=True, help_text='GHL location ID for this simulator package', max_length=100, null=True),
        ),
    ]
