# Generated by Django 5.2.8 on 2025-12-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0013_coachingpackage_location_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppurchase',
            name='package_type',
            field=models.CharField(blank=True, choices=[('coaching', 'Coaching'), ('simulator', 'Simulator')], help_text="Type of package: 'coaching' or 'simulator'. Explicitly stored to avoid ambiguity when both package types exist with same ID.", max_length=20, null=True),
        ),
    ]
