# Generated by Django 5.2.8 on 2025-12-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0019_change_expiry_date_to_validity_days'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='simulatorpackageusage',
            new_name='coaching_si_package_0af216_idx',
            old_name='coaching_si_package_6a8b3d_idx',
        ),
        migrations.AlterField(
            model_name='simulatorpackageusage',
            name='hours_used',
            field=models.DecimalField(decimal_places=2, help_text='Number of hours used in this booking', max_digits=6),
        ),
    ]
