# Generated by Django 5.2.8 on 2026-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0020_rename_coaching_si_package_6a8b3d_idx_coaching_si_package_0af216_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='is_tpi_assessment',
            field=models.BooleanField(default=False, help_text='If True, this package is categorized as a TPI Assessment package (non-transferable, personal use only)'),
        ),
    ]
