# Generated by Django 5.2.8 on 2026-02-18 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0021_coachingpackage_is_tpi_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorpackagepurchase',
            name='referral_id',
            field=models.ForeignKey(blank=True, help_text='Staff member who referred this purchase (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_simulator_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
