# Generated by Django 5.2.8 on 2026-04-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_seed_default_service_categories"),
        ("coaching", "0022_simulatorpackagepurchase_referral_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachingpackage",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Service category this package belongs to (Phase C).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coaching_packages",
                to="categories.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="simulatorpackage",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Service category this package belongs to (Phase C).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulator_packages",
                to="categories.servicecategory",
            ),
        ),
    ]
