# Generated by Django 5.2.8 on 2026-06-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0025_add_category_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorpackage',
            name='is_membership',
            field=models.BooleanField(default=False, help_text='If True, this package is a recurring monthly membership (billed via Square Subscriptions API).'),
        ),
        migrations.AddField(
            model_name='simulatorpackage',
            name='monthly_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Simulator hours granted each billing cycle (memberships only). Resets on every renewal — no carry-over.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='simulatorpackage',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of simulator hours included in this package (one-time). For memberships, use monthly_hours instead.', max_digits=6),
        ),
    ]
