# Generated by Django 5.2.8 on 2026-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0026_add_membership_fields_to_simulator_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='is_membership',
            field=models.BooleanField(default=False, help_text='If True, this package is a recurring monthly membership (billed via Square Subscriptions API).'),
        ),
        migrations.AddField(
            model_name='coachingpackage',
            name='monthly_category_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Category asset hours granted each billing cycle (memberships only). Resets on every renewal — no carry-over.', max_digits=6),
        ),
        migrations.AddField(
            model_name='coachingpackage',
            name='monthly_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Coaching sessions granted each billing cycle (memberships only). Resets on every renewal — no carry-over.'),
        ),
        migrations.AddField(
            model_name='coachingpackage',
            name='monthly_simulator_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Simulator hours granted each billing cycle (memberships only). Resets on every renewal — no carry-over.', max_digits=6),
        ),
    ]
