# Generated by Django 5.2.8 on 2026-07-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0027_coachingpackage_is_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='hide_price_on_card',
            field=models.BooleanField(default=False, help_text='If True, hides the price on the package card but shows it in the checkout modal.'),
        ),
        migrations.AddField(
            model_name='simulatorpackage',
            name='hide_price_on_card',
            field=models.BooleanField(default=False, help_text='If True, hides the price on the package card but shows it in the checkout modal.'),
        ),
    ]
