# Generated by Django 5.2.8 on 2026-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0028_coachingpackage_hide_price_on_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingpackage',
            name='is_one_off',
            field=models.BooleanField(default=False, help_text='Staff Quick Checkout one-off package. Hidden from public/online catalog listings.'),
        ),
        migrations.AddField(
            model_name='simulatorpackage',
            name='is_one_off',
            field=models.BooleanField(default=False, help_text='Staff Quick Checkout one-off package. Hidden from public/online catalog listings.'),
        ),
    ]
