# Generated by Django 5.2.8 on 2025-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghllocation',
            name='access_token',
            field=models.TextField(blank=True, help_text='OAuth access token'),
        ),
        migrations.AddField(
            model_name='ghllocation',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='OAuth refresh token'),
        ),
        migrations.AddField(
            model_name='ghllocation',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the access token expires', null=True),
        ),
    ]
