# Generated by Django 5.2.8 on 2026-03-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl', '0002_ghllocation_access_token_ghllocation_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghllocation',
            name='timezone',
            field=models.CharField(default='America/Halifax', help_text='IANA timezone for this golf center (e.g. America/Halifax, America/Toronto, Asia/Dubai)', max_length=100),
        ),
    ]
