# Generated by Django 5.2.8 on 2026-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl', '0006_add_refund_policy_to_ghllocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghllocation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.14, help_text='Tax rate as a decimal fraction (e.g. 0.14 for 14% HST). Applied to all Square payments at this location.', max_digits=5),
        ),
    ]
