# Generated by Django 5.2.8 on 2026-07-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl', '0007_add_tax_rate_to_ghllocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghllocation',
            name='notifications_location',
            field=models.ForeignKey(blank=True, help_text="GHL subaccount to push all notifications for this center's users through. If blank, uses this location's own credentials.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_targets', to='ghl.ghllocation'),
        ),
    ]
